name: Run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tests/run-tests.sh